server:
  shutdown: graceful

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true