server:
  shutdown: graceful

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: account_email
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: kakao_account
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize

  mvc:
    throw-exception-if-no-handler-found: true
    converters:
      preferred-json-mapper: jackson
  web:
    resources:
      add-mappings: false

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket-name: ${AWS_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false
      sns:
        region: ${AWS_SNS_REGION}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

auth:
  redirect-base-uri: http://localhost:8080/
  redirect-login-failure-uri: http://localhost:8080/auth/error
  redirect-admin-uri: http://localhost:8080/admin
  allowed-origins:
    - '*'
  loginEndPointBaseUri: /auth/v3/oauth2/authorization
  loginProcessingUri: /login/oauth2/code/*

schedule:
  startReceptionDate: ${START_RECEPTION_DATE}
  endReceptionDate: ${END_RECEPTION_DATE}

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: ${ACTUATOR_BASE_PATH}
