server:
  shutdown: graceful

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: account_email
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: kakao_account
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize

auth:
  redirect-base-uri: http://localhost:8080/
  redirect-login-failure-uri: http://localhost:8080/auth/error
  redirect-admin-uri: http://localhost:8080/admin
  allowed-origins:
    - '*'