name: HelloGSM prod CI Workflow

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Gradle's permission
        run: chmod +x gradlew

      - name: Make yml file
        run: touch ./src/main/resources/application-prod.yml
          
          echo "${{ secrets.PROD_WEB_YML }}" > ./src/main/resources/application-prod.yml

        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: CI Success Notification
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0x4CAF50

      - name: CI Failure Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0xFF4C4C