name: HelloGSM prod CI Workflow

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Gradle's permission
        run: chmod +x gradlew

      - name: Make yml file
        run: touch ./src/main/resources/application-prod.yml
          
          echo "${{ secrets.PROD_WEB_YML }}" > ./src/main/resources/application-prod.yml

        shell: bash

      # Run build and tests without packaging
      - name: Run Build and Tests
        run: ./gradlew assemble